# Generated by Django 5.2.11 on 2026-02-25 08:35

import django.db.models.deletion
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(default=games.models.generate_game_id, max_length=20, primary_key=True, serialize=False)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('result', models.CharField(choices=[('WON', 'Won'), ('LOST', 'Lost'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='TSh', max_length=10)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=10)),
                ('active_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('bet_type', models.CharField(default='Accumulator', max_length=20)),
                ('total_odds', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('match_ref', models.CharField(max_length=10)),
                ('teams', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=50)),
                ('selection', models.CharField(max_length=100)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='games.game')),
            ],
            options={
                'unique_together': {('game', 'match_ref')},
            },
        ),
    ]
