# Generated by Django 5.2.11 on 2026-02-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.IntegerField(unique=True)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('homeTeam', models.CharField(max_length=100)),
                ('awayTeam', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=200)),
                ('homeOdds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drawOdds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('awayOdds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('betCount', models.IntegerField(default=0)),
                ('hasBoostedOdds', models.BooleanField(default=False)),
                ('hasTwoUp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
