# Generated by Django 5.2.11 on 2026-02-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_matchfixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchfixture',
            name='awayOddsFire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchfixture',
            name='drawOddsFire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchfixture',
            name='homeOddsFire',
            field=models.BooleanField(default=False),
        ),
    ]
